# Generated by Django 3.1.4 on 2020-12-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='data_expiracao',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
