# Generated by Django 3.1.4 on 2020-12-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='data_expiracao',
            field=models.CharField(max_length=50),
        ),
    ]
